### PR TITLE
feat: user and session ids

### LINKED ISSUE #156: Feature Request: Get User and Session IDs
It would be useful to be able to retrieve the user/session IDs so that I can provide them in error messages. 

It looks like they are stored in cookies by default but I guess that is flexible.

I am happy to add this if you'd accept?

### PR DESCRIPTION
**Pull request by tdashworth**
Resolves #156.

### CODE REVIEW

**Comment by IvanJosipovic** [comment]
Hey, thanks for this PR, do you mind also trying to write up some tests for this?

We need to make sure these calls don't throw exceptions if the app insight js is blocked etc.

**Comment by tdashworth** [comment]
They don't make calls from what I can tell.

I could assert the `userId` against the hardcoded one?

**Comment by IvanJosipovic** [comment]
> They don't make calls from what I can tell.
> 
> I could assert the `userId` against the hardcoded one?

We have a command to set the User ID, https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/2f2a40e101e4d00fd860dbe483d8d3a6bff74871/src/BlazorApplicationInsights/IApplicationInsights.cs#LL140C14-L140C41

For the UserId we could do something like this:
- The sample has a button which runs "SetAuthenticatedUserContext"
- Create another button which runs GetUserId and sets the value on the page
- The test should trigger the two buttons and read the value from the page

**Comment by tdashworth** [comment]
@IvanJosipovic tests added 😄

**Pull request merged**
